config:
  - torchwm/configs/**

# Add 'environment' to any changes to environment files
environment:
  - torchwm/envs/**

trainer:
  - torchwm/training/**

controller:
  - torchwm/controller/**

helpers:
  - torchwm/helpers/**

tokenizers:
  - torchwm/vision/video_tokenizer.py
  - torchwm/vision/vq_layer.py

tests:
  - tests/**
  - torchwm/testing/**

models:
  - torchwm/models/**

memory:
  - torchwm/memory/**

masks:
  - torchwm/masks/**

reward_functions:
  - torchwm/reward/**

observation_wrappers:
  - torchwm/observations/**

utilities:
  - torchwm/utils/**

vision:
  - torchwm/vision/**

transforms:
  - torchwm/transforms/**

# Add 'CI/CD' to any changes to GitHub workflows and automation config
CI/CD:
  - .github/workflows/**
  - .github/*.yml

# Add 'documentation' to any changes to documentation files
documentation:
  - README.md
  - CITATION.cff
  - LICENSE
  - docs/**
