"""Typing stub for the friendly ``torchwm`` public package.

Generated by ``python -m tools.gen_type_stub`` - do not edit by hand.

``torchwm`` resolves its public surface lazily at runtime, so every export has
to be spelled out here for type checkers and autocomplete to see it.
"""

from typing import Any

from torchwm import api as api

from torchwm.api import ENV_BACKEND_SPECS as ENV_BACKEND_SPECS
from torchwm.api import EnvBackendSpec as EnvBackendSpec
from torchwm.api import MODEL_SPECS as MODEL_SPECS
from torchwm.api import ModelSpec as ModelSpec
from torchwm.api import create_config as create_config
from torchwm.api import create_model as create_model
from torchwm.api import get_env_backend_spec as get_env_backend_spec
from torchwm.api import get_model_spec as get_model_spec
from torchwm.api import list_env_backends as list_env_backends
from torchwm.api import list_envs as list_envs
from torchwm.api import list_models as list_models
from torchwm.api import make_env as make_env
from torchwm.blocks.mhsa import MultiHeadSelfAttention as MultiHeadAttention
from torchwm.blocks.mhsa import MultiHeadSelfAttention as MultiHeadSelfAttention
from torchwm.blocks.st_transformer import STTransformer as STTransformer
from torchwm.configs.diamond_config import ATARI_100K_GAMES as ATARI_100K_GAMES
from torchwm.configs.diamond_config import DiamondConfig as DiamondConfig
from torchwm.configs.diamond_config import HUMAN_SCORES as HUMAN_SCORES
from torchwm.configs.diamond_config import RANDOM_SCORES as RANDOM_SCORES
from torchwm.configs.dit_config import DiTConfig as DiTConfig
from torchwm.configs.dit_config import dit_preset_config as dit_preset_config
from torchwm.configs.dit_config import get_dit_config as get_dit_config
from torchwm.configs.dit_config import list_dit_presets as list_dit_presets
from torchwm.configs.dreamer_config import DreamerConfig as DreamerConfig
from torchwm.configs.genie_config import DynamicsModelConfig as DynamicsModelConfig
from torchwm.configs.genie_config import GenieConfig as GenieConfig
from torchwm.configs.genie_config import GenieSmallConfig as GenieSmallConfig
from torchwm.configs.genie_config import LatentActionModelConfig as LatentActionModelConfig
from torchwm.configs.genie_config import STTransformerConfig as STTransformerConfig
from torchwm.configs.genie_config import VideoTokenizerConfig as VideoTokenizerConfig
from torchwm.configs.iris_config import IRISConfig as IRISConfig
from torchwm.configs.jepa_config import JEPAConfig as JEPAConfig
from torchwm.controller.iris_policy import CNNFeatureExtractor as CNNFeatureExtractor
from torchwm.controller.iris_policy import IRISActor as IRISActor
from torchwm.controller.iris_policy import IRISCritic as IRISCritic
from torchwm.controller.iris_policy import IRISPolicy as IRISPolicy
from torchwm.controller.rollout_generator import RolloutGenerator as RolloutGenerator
from torchwm.controller.rssm_policy import RSSMPolicy as RSSMPolicy
from torchwm.envs.ale_atari_env import list_available_atari_envs as list_available_atari_envs
from torchwm.envs.ale_atari_env import make_atari_env as make_atari_env
from torchwm.envs.ale_atari_vector_env import make_atari_vector_env as make_atari_vector_env
from torchwm.envs.brax_env import BraxImageEnv as BraxImageEnv
from torchwm.envs.brax_env import make_brax_env as make_brax_env
from torchwm.envs.bsuite_env import BSuiteImageEnv as BSuiteImageEnv
from torchwm.envs.bsuite_env import list_available_bsuite_ids as list_available_bsuite_ids
from torchwm.envs.bsuite_env import make_bsuite_env as make_bsuite_env
from torchwm.envs.diamond_atari import make_diamond_atari_env as make_diamond_atari_env
from torchwm.envs.dmc import DeepMindControlEnv as DeepMindControlEnv
from torchwm.envs.dmlab import DMLAB_LEVELS as DMLAB_LEVELS
from torchwm.envs.dmlab import DMLabEnv as DMLabEnv
from torchwm.envs.dmlab import make_dmlab_env as make_dmlab_env
from torchwm.envs.gym_env import GymImageEnv as GymImageEnv
from torchwm.envs.gym_env import make_gym_env as make_gym_env
from torchwm.envs.mujoco_env import MuJoCoImageEnv as MuJoCoImageEnv
from torchwm.envs.mujoco_env import MuJoCoImageEnv as MujocoEnv
from torchwm.envs.mujoco_env import make_mujoco_env as make_mujoco_env
from torchwm.envs.mujoco_env import make_mujoco_env_from_config as make_mujoco_env_from_config
from torchwm.envs.robotics_env import list_gymnasium_robotics_envs as list_gymnasium_robotics_envs
from torchwm.envs.robotics_env import make_robotics_env as make_robotics_env
from torchwm.envs.robotics_env import register_gymnasium_robotics_envs as register_gymnasium_robotics_envs
from torchwm.envs.unity_env import UnityMLAgentsEnv as UnityMLAgentsEnv
from torchwm.envs.unity_env import make_unity_mlagents_env as make_unity_mlagents_env
from torchwm.envs.world_model_env import WorldModelEnv as WorldModelEnv
from torchwm.envs.world_model_env import make_world_model_env as make_world_model_env
from torchwm.envs.wrappers import ActionRepeat as ActionRepeat
from torchwm.envs.wrappers import NormalizeActions as NormalizeActions
from torchwm.envs.wrappers import ObsDict as ObsDict
from torchwm.envs.wrappers import OneHotAction as OneHotAction
from torchwm.envs.wrappers import RenderImage as RenderImage
from torchwm.envs.wrappers import ResizeImage as ResizeImage
from torchwm.envs.wrappers import RewardObs as RewardObs
from torchwm.envs.wrappers import SelectAction as SelectAction
from torchwm.envs.wrappers import TimeLimit as TimeLimit
from torchwm.export import ExportableAgentMixin as ExportableAgentMixin
from torchwm.export import export_any as export_any
from torchwm.export import export_model as export_model
from torchwm.layers.ada_ln_norm import AdaLNNormalization as AdaLNNormalization
from torchwm.layers.rms_norm import RMSNorm as RMSNorm
from torchwm.memory.dreamer_memory import ReplayBuffer as ReplayBuffer
from torchwm.memory.iris_memory import IRISOnPolicyBuffer as IRISOnPolicyBuffer
from torchwm.memory.iris_memory import IRISReplayBuffer as IRISReplayBuffer
from torchwm.memory.planet_memory import Episode as Episode
from torchwm.memory.planet_memory import Memory as Memory
from torchwm.models.diffusion.DDPM import DDPM as DDPM
from torchwm.models.diffusion.DiT import DiT as DiT
from torchwm.models.diffusion.DiT import PatchEmbed as PatchEmbed
from torchwm.models.diffusion.DiT import PatchUnEmbed as PatchUnEmbed
from torchwm.models.diffusion.DiT import create_dit as create_dit
from torchwm.models.diffusion.DiT import sinusoidal_time_embedding as sinusoidal_time_embedding
from torchwm.models.diffusion.actor_critic import ActorCriticNetwork as ActorCriticNetwork
from torchwm.models.diffusion.reward_termination import RewardTerminationModel as RewardTerminationModel
from torchwm.models.dreamer import Dreamer as Dreamer
from torchwm.models.dreamer import DreamerAgent as DreamerAgent
from torchwm.models.dreamer import DreamerAgent as DreamerV3
from torchwm.models.dreamer import preprocess_obs as preprocess_obs
from torchwm.models.dreamer_rssm import RSSM as DreamerRSSM
from torchwm.models.dreamer_rssm import RSSM as RSSM
from torchwm.models.dreamer_v1 import DreamerV1 as DreamerV1
from torchwm.models.dreamer_v2 import DreamerV2 as DreamerV2
from torchwm.models.dynamics_model import DynamicsModel as DynamicsModel
from torchwm.models.dynamics_model import create_dynamics_model as create_dynamics_model
from torchwm.models.genie import Genie as Genie
from torchwm.models.genie import create_genie as create_genie
from torchwm.models.genie import create_genie_large as create_genie_large
from torchwm.models.genie import create_genie_small as create_genie_small
from torchwm.models.iris_agent import IRISAgent as IRISAgent
from torchwm.models.iris_agent import compute_lambda_return as compute_lambda_return
from torchwm.models.iris_transformer import IRISTransformer as IRISTransformer
from torchwm.models.iris_transformer import IRISWorldModel as IRISWorldModel
from torchwm.models.jepa_agent import JEPAAgent as JEPAAgent
from torchwm.models.latent_action_model import LatentActionModel as LatentActionModel
from torchwm.models.latent_action_model import create_latent_action_model as create_latent_action_model
from torchwm.models.modular_rssm import ModularRSSM as ModularRSSM
from torchwm.models.modular_rssm import create_modular_rssm as create_modular_rssm
from torchwm.models.planet import Planet as Planet
from torchwm.models.rssm import RecurrentStateSpaceModel as RecurrentStateSpaceModel
from torchwm.models.vit import VisionTransformer as VisionTransformer
from torchwm.registry import deregister_env_backend as deregister_env_backend
from torchwm.registry import deregister_world_model as deregister_world_model
from torchwm.registry import get_registered_model_spec as get_registered_model_spec
from torchwm.registry import list_registered_env_backends as list_registered_env_backends
from torchwm.registry import list_registered_models as list_registered_models
from torchwm.registry import register_env_backend as register_env_backend
from torchwm.registry import register_world_model as register_world_model
from torchwm.reward.dreamer_v1_reward import RewardModel as DreamerRewardModel
from torchwm.reward.dreamer_v1_reward import RewardModel as RewardModel
from torchwm.reward.dreamer_v1_value import ValueModel as DreamerValueModel
from torchwm.reward.dreamer_v1_value import ValueModel as ValueModel
from torchwm.training.eval_jepa import jepa_linear_probe as jepa_linear_probe
from torchwm.training.eval_jepa import load_jepa_encoder as load_jepa_encoder
from torchwm.utils.deprecation import deprecated as deprecated
from torchwm.utils.deprecation import deprecated_class as deprecated_class
from torchwm.utils.deprecation import deprecated_function as deprecated_function
from torchwm.utils.dreamer_utils import FreezeParameters as FreezeParameters
from torchwm.utils.dreamer_utils import Logger as Logger
from torchwm.utils.dreamer_utils import compute_return as compute_return
from torchwm.utils.memory_utils import enable_performance_defaults as enable_performance_defaults
from torchwm.utils.memory_utils import maybe_compile as maybe_compile
from torchwm.utils.memory_utils import to_channels_last as to_channels_last
from torchwm.utils.throughput import ThroughputMeter as ThroughputMeter
from torchwm.utils.throughput import measure_steps as measure_steps
from torchwm.utils.throughput import tensor_nbytes as tensor_nbytes
from torchwm.vision.dreamer_decoder import ActionDecoder as ActionDecoder
from torchwm.vision.dreamer_decoder import ConvDecoder as ConvDecoder
from torchwm.vision.dreamer_decoder import DenseDecoder as DenseDecoder
from torchwm.vision.dreamer_decoder import SampleDist as SampleDist
from torchwm.vision.dreamer_decoder import TanhBijector as TanhBijector
from torchwm.vision.dreamer_encoder import ConvEncoder as ConvEncoder
from torchwm.vision.iris_decoder import IRISDecoder as IRISDecoder
from torchwm.vision.iris_encoder import IRISEncoder as IRISEncoder
from torchwm.vision.perceptual_loss import LPIPSPerceptualLoss as LPIPSPerceptualLoss
from torchwm.vision.perceptual_loss import build_perceptual_loss as build_perceptual_loss
from torchwm.vision.planet_decoder import CNNDecoder as CNNDecoder
from torchwm.vision.planet_encoder import CNNEncoder as CNNEncoder
from torchwm.vision.video_tokenizer import VideoTokenizer as VideoTokenizer
from torchwm.vision.video_tokenizer import create_video_tokenizer as create_video_tokenizer
from torchwm.vision.vq_layer import VectorQuantizer as VectorQuantizer
from torchwm.vision.vq_layer import VectorQuantizerEMA as VectorQuantizerEMA

__version__: str

def __getattr__(name: str) -> Any: ...


__all__ = [
    "ATARI_100K_GAMES",
    "ActionDecoder",
    "ActionRepeat",
    "ActorCriticNetwork",
    "AdaLNNormalization",
    "BSuiteImageEnv",
    "BraxImageEnv",
    "CNNDecoder",
    "CNNEncoder",
    "CNNFeatureExtractor",
    "ConvDecoder",
    "ConvEncoder",
    "DDPM",
    "DMLAB_LEVELS",
    "DMLabEnv",
    "DeepMindControlEnv",
    "DenseDecoder",
    "DiT",
    "DiTConfig",
    "DiamondConfig",
    "Dreamer",
    "DreamerAgent",
    "DreamerConfig",
    "DreamerRSSM",
    "DreamerRewardModel",
    "DreamerV1",
    "DreamerV2",
    "DreamerV3",
    "DreamerValueModel",
    "DynamicsModel",
    "DynamicsModelConfig",
    "ENV_BACKEND_SPECS",
    "EnvBackendSpec",
    "Episode",
    "ExportableAgentMixin",
    "FreezeParameters",
    "Genie",
    "GenieConfig",
    "GenieSmallConfig",
    "GymImageEnv",
    "HUMAN_SCORES",
    "IRISActor",
    "IRISAgent",
    "IRISConfig",
    "IRISCritic",
    "IRISDecoder",
    "IRISEncoder",
    "IRISOnPolicyBuffer",
    "IRISPolicy",
    "IRISReplayBuffer",
    "IRISTransformer",
    "IRISWorldModel",
    "JEPAAgent",
    "JEPAConfig",
    "LPIPSPerceptualLoss",
    "LatentActionModel",
    "LatentActionModelConfig",
    "Logger",
    "MODEL_SPECS",
    "Memory",
    "ModelSpec",
    "ModularRSSM",
    "MuJoCoImageEnv",
    "MujocoEnv",
    "MultiHeadAttention",
    "MultiHeadSelfAttention",
    "NormalizeActions",
    "ObsDict",
    "OneHotAction",
    "PatchEmbed",
    "PatchUnEmbed",
    "Planet",
    "RANDOM_SCORES",
    "RMSNorm",
    "RSSM",
    "RSSMPolicy",
    "RecurrentStateSpaceModel",
    "RenderImage",
    "ReplayBuffer",
    "ResizeImage",
    "RewardModel",
    "RewardObs",
    "RewardTerminationModel",
    "RolloutGenerator",
    "STTransformer",
    "STTransformerConfig",
    "SampleDist",
    "SelectAction",
    "TanhBijector",
    "ThroughputMeter",
    "TimeLimit",
    "UnityMLAgentsEnv",
    "ValueModel",
    "VectorQuantizer",
    "VectorQuantizerEMA",
    "VideoTokenizer",
    "VideoTokenizerConfig",
    "VisionTransformer",
    "WorldModelEnv",
    "__version__",
    "api",
    "build_perceptual_loss",
    "compute_lambda_return",
    "compute_return",
    "create_config",
    "create_dit",
    "create_dynamics_model",
    "create_genie",
    "create_genie_large",
    "create_genie_small",
    "create_latent_action_model",
    "create_model",
    "create_modular_rssm",
    "create_video_tokenizer",
    "deprecated",
    "deprecated_class",
    "deprecated_function",
    "deregister_env_backend",
    "deregister_world_model",
    "dit_preset_config",
    "enable_performance_defaults",
    "export_any",
    "export_model",
    "get_dit_config",
    "get_env_backend_spec",
    "get_model_spec",
    "get_registered_model_spec",
    "jepa_linear_probe",
    "list_available_atari_envs",
    "list_available_bsuite_ids",
    "list_dit_presets",
    "list_env_backends",
    "list_envs",
    "list_gymnasium_robotics_envs",
    "list_models",
    "list_registered_env_backends",
    "list_registered_models",
    "load_jepa_encoder",
    "make_atari_env",
    "make_atari_vector_env",
    "make_brax_env",
    "make_bsuite_env",
    "make_diamond_atari_env",
    "make_dmlab_env",
    "make_env",
    "make_gym_env",
    "make_mujoco_env",
    "make_mujoco_env_from_config",
    "make_robotics_env",
    "make_unity_mlagents_env",
    "make_world_model_env",
    "maybe_compile",
    "measure_steps",
    "preprocess_obs",
    "register_env_backend",
    "register_gymnasium_robotics_envs",
    "register_world_model",
    "sinusoidal_time_embedding",
    "tensor_nbytes",
    "to_channels_last",
]
