"""Generate ``torchwm/__init__.pyi`` from the public export map.

``torchwm`` resolves its public surface through a lazy module-level
``__getattr__``.  Type checkers read source, not runtime, so none of those
names are visible to them - which is why the shipped stub has to spell every
export out explicitly.

Each ``__all__`` entry is re-exported from the module that *statically defines*
it, so a checker can follow the import.  That is not always the module named in
the export map: ``torchwm.models`` and ``torchwm.envs`` are lazy too,
so the stub reaches through to the concrete implementation module instead.

Run ``python -m tools.gen_type_stub`` to rewrite the stub, or
``python -m tools.gen_type_stub --check`` to verify it is up to date (this is
what ``tests/test_type_stub.py`` does).
"""

from __future__ import annotations

import argparse
import ast
import importlib
import sys
from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
STUB_PATH = REPO_ROOT / "torchwm" / "__init__.pyi"

HEADER = '''"""Typing stub for the friendly ``torchwm`` public package.

Generated by ``python -m tools.gen_type_stub`` - do not edit by hand.

``torchwm`` resolves its public surface lazily at runtime, so every export has
to be spelled out here for type checkers and autocomplete to see it.
"""

from typing import Any

from torchwm import api as api
'''


def _bound_names(node: ast.AST) -> set[str]:
    """Names a module body binds at the top level.

    ``if``/``try`` wrappers are walked into: optional-dependency shims are
    routinely defined inside them.
    """

    names: set[str] = set()
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(child.name)
        elif isinstance(child, (ast.Import, ast.ImportFrom)):
            names.update(a.asname or a.name.split(".")[0] for a in child.names)
        elif isinstance(child, ast.Assign):
            for target in child.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(child, ast.AnnAssign):
            if isinstance(child.target, ast.Name):
                names.add(child.target.id)
        elif isinstance(child, (ast.If, ast.Try)):
            names |= _bound_names(child)
    return names


@lru_cache(maxsize=None)
def _statically_defined(module_name: str) -> frozenset[str]:
    """Top-level names a type checker can see in ``module_name``'s source."""

    try:
        module = importlib.import_module(module_name)
    except Exception:  # pragma: no cover - unimportable module cannot be a source
        return frozenset()
    source_file = getattr(module, "__file__", None)
    if not source_file:
        return frozenset()
    try:
        tree = ast.parse(Path(source_file).read_text(encoding="utf-8"))
    except (OSError, SyntaxError):  # pragma: no cover - defensive
        return frozenset()
    return frozenset(_bound_names(tree))


def _origin(name: str, obj: Any, mapped_module: str) -> tuple[str, str] | None:
    """Return ``(module, original_name)`` a checker can import ``obj`` from."""

    # The name the object is defined under may differ from the exported alias
    # (``DreamerRSSM`` is ``RSSM`` in ``torchwm.models.dreamer_rssm``).
    qualname = getattr(obj, "__qualname__", "")
    defined_as = qualname.split(".")[0] if qualname else name

    candidates: list[tuple[str, str]] = []
    defining_module = getattr(obj, "__module__", None)
    if defining_module:
        candidates.append((defining_module, defined_as))
    candidates.append((mapped_module, name))
    # Constants carry no ``__module__``.  Resolving ``name`` above already
    # imported whichever submodule defines it, so identity against the loaded
    # submodules of the mapped package finds it without importing anything new.
    prefix = f"{mapped_module}."
    for loaded_name, loaded in sorted(sys.modules.items()):
        if loaded_name.startswith(prefix) and getattr(loaded, name, None) is obj:
            candidates.append((loaded_name, name))

    for module_name, symbol in candidates:
        if symbol in _statically_defined(module_name):
            return module_name, symbol
    return None


def _export_map() -> dict[str, str]:
    torchwm = importlib.import_module("torchwm")
    return dict(torchwm._EXPORTS)  # noqa: SLF001 - this is the source of truth


class MissingOptionalBackends(RuntimeError):
    """The export map cannot be fully resolved in this environment.

    Generating from a partial environment would quietly drop every export whose
    backend is not installed, and ``py.typed`` makes type checkers trust the
    result completely - so refuse instead of shipping a truncated stub.
    """


def render_stub() -> str:
    import torchwm

    export_map = _export_map()
    imports: dict[str, list[tuple[str, str]]] = defaultdict(list)
    untypeable: list[str] = []
    unresolved: list[str] = []

    for name in sorted(export_map):
        try:
            obj = getattr(torchwm, name)
        except Exception as exc:  # noqa: BLE001 - reported together below
            unresolved.append(f"{name} ({type(exc).__name__}: {exc})")
            continue
        origin = _origin(name, obj, export_map[name])
        if origin is None:
            untypeable.append(name)
            continue
        module_name, symbol = origin
        imports[module_name].append((symbol, name))

    if unresolved:
        raise MissingOptionalBackends(
            "cannot resolve "
            f"{len(unresolved)} export(s) in this environment, so the stub would "
            "be incomplete. Install every backend first:\n"
            '    pip install -e ".[all]"\n'
            "Unresolved: " + ", ".join(unresolved)
        )

    lines = [HEADER]
    for module_name in sorted(imports):
        for symbol, alias in sorted(imports[module_name], key=lambda pair: pair[1]):
            lines.append(f"from {module_name} import {symbol} as {alias}")
    lines.append("")
    lines.append("__version__: str")
    for name in untypeable:
        # Better an explicit ``Any`` than a name a checker reports as missing.
        lines.append(f"{name}: Any")
    lines.append("")

    # ``torchwm.<submodule>`` is resolved by a meta-path alias finder, which no
    # checker can follow - keep the fallback so those stay usable.
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")

    all_entries = sorted(set(torchwm.__all__))
    lines.append("")
    lines.append("__all__ = [")
    lines.extend(f'    "{entry}",' for entry in all_entries)
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed stub is stale",
    )
    args = parser.parse_args(argv)

    rendered = render_stub()
    if args.check:
        current = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.exists() else ""
        if current != rendered:
            print(
                f"{STUB_PATH.relative_to(REPO_ROOT)} is out of date; "
                "run `python -m tools.gen_type_stub`",
                file=sys.stderr,
            )
            return 1
        return 0

    STUB_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {STUB_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
